:sectnums:
:sectnumlevels: 5
:toc: left
:toclevels: 3
:page-layout: docs

= Bag Database User API

== Using the Bag Database's API

The Bag Database's API should be straightforward to use.  There are a few rules
of thumb to keep in mind:

1. `GET` requests retrieve data; `POST` requests modify something in the database.
2. If you submit any `POST` requests, you must have an active session and
include a CSRF token.
3. If authentication is enabled, you must log in before making any other
requests.

=== Setup
For the sake of convenience, these examples will store the base URL of the Bag Database
in an environment variable named `URL`.
----
$ URL=http://localhost:8080/
----

=== Requesting a CSRF Token
This GET request will:

1. Start a session and save the session variable in cookie jar
2. Parse the CSRF token from the output
3. Place it in a shell variable named `CSRF`
----
$ CSRF=`curl -s -L -X GET -c cookies.txt ${URL} | sed -rn 's/^.*(value=|csrfToken = )"([-a-z0-9]*)".*$/\2/p'`
----

=== Logging In
If authentication is required, this will use the session we just established and log in.  A couple things to note:
1. The URL is different depending on whether LDAP authentication is enabled
2. You may be issued a new CSRF token that replaces the previous one
----
# Not using LDAP:
$ CSRF=`curl -s -c cookies.txt -b cookies.txt \
    -F "username=admin" -F "password=letmein" -F "_csrf=${CSRF}" \
    -L ${URL}/signin | sed -rn 's/^.*csrfToken = "([-a-z0-9]*)".*$/\1/p'`

# Using LDAP:
$ CSRF=`curl -s -c cookies.txt -b cookies.txt \
    -F "username=admin" -F "password=letmein" -F "_csrf=${CSRF}" \
    -L ${URL}/ldap_login | sed -rn 's/^.*csrfToken = "([-a-z0-9]*)".*$/\1/p'`
----

=== Performing an Authenticated Request
After you have an authenticated session, you can use that cookie jar to make requests.
----
$ curl -s -c cookies.txt -b cookies.txt -X GET \
    "${URL}/bags/search?text=&page=1&start=0&limit=100&sort=filename&dir=ASC"
----

Note that if you are making a POST request, you must include a parameter named `_csrf` that
is set to the previously obtained token.
----
$ curl -s -c cookies.txt -b cookies.txt \
    -F "scriptId=1" -F "bagIds=1,2,3" -F "_csrf=${CSRF}" \
    -X POST "${URL}/scripts/run"
----
[[bags]]
== Bags
include::bags.adoc[]

[[scripts]]
== Scripts
include::scripts.adoc[]
