version: '3.6'
services:
    traefik:
        image: traefik:v2.4
        command:
            - --api.insecure=true
            - --providers.docker
            - --entrypoints.web.address=:80
            - --entrypoints.websecure.address=:443
            - --entrypoints.web.http.redirections.entrypoint.to=websecure
            - --entrypoints.web.http.redirections.entrypoint.scheme=https
            - --certificatesresolvers.bagdbresolver.acme.email=youremail@example.com
            - --certificatesresolvers.bagdbresolver.acme.storage=/etc/traefik/acme/acme.json
            - --certificatesresolvers.bagdbresolver.acme.httpchallenge.entrypoint=web
        networks:
            - bagdb
        ports:
            - "80:80"
            - "443:443"
            - "8080:8080"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - acme:/etc/traefik/acme
    docker:
        image: docker:dind
        privileged: yes
        networks:
            - bagdb
        volumes:
            - bags:/bags:ro # Needs to match the path in the bagdb container
            - scripts:/scripts
            - docker_cache:/var/lib/docker
        command: ["dockerd", "--host=tcp://0.0.0.0:2375"]
    bagdb:
        image: ghcr.io/swri-robotics/bag-database:latest
        networks:
            - bagdb
        depends_on:
            - postgres
            - openldap
        labels:
            - "traefik.http.routers.bagdb.rule=Host(`bagdb.exaple.com`)"
            - "traefik.http.routers.bagdb.tls=true"
            - "traefik.http.routers.bagdb.tls.certresolver=bagdbresolver"
        volumes:
            - bags:/bags
            - indexes:/root/.ros-bag-database/indexes
            - scripts:/scripts
        env_file:
            - bagdb.env
    postgres:
        image: postgis/postgis:11-2.5
        networks:
            - bagdb
        volumes:
            - postgres:/var/lib/postgresql/data
        env_file:
            - postgres.env
    openldap:
        image: osixia/openldap:1.3.0
        networks:
            - bagdb
        volumes:
            - ldap:/var/lib/ldap
            - slapd:/etc/ldap/slapd.d
        ports:
            - "389:389"
            - "636:636"
            # These ports are exposed so you can easily connect to the container to add
            # data by, for example, using the LDIF files below.  You can hide these ports
            # if you don't need to connect to the container, or perhaps even add another
            # web server behind the reverse proxy to act as an LDAP administration interface.
        env_file:
            - openldap.env
    webviz:
        image: cruise/webviz
        networks:
            - bagdb
        volumes:
            - ./webviz-default.conf:/etc/nginx/conf.d/default.conf:ro
        labels:
            - "traefik.http.routers.webviz.rule=Host(`bagdb.example.com`) && PathPrefix(`/webviz`)"
            - "traefik.http.routers.webviz.tls=true"
            - "traefik.http.routers.webviz.tls.certresolver=bagdbresolver"
            - "traefik.http.services.webviz.loadbalancer.server.port=8080"
networks:
    bagdb: {}
volumes:
    acme:
    bags:
    docker_cache:
    postgres:
    ldap:
    slapd:
    indexes:
    scripts:
        driver_opts:
            type: 'tmpfs'
            device: 'tmpfs'
  